[package]
name = "tests-scripts-lib"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
godot-rust-script = { path = "../rust-script", features = ["scripts"] }

[lints]
workspace = true
